import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import glob from 'glob-promise';

const CONTENT_DIR = 'content/blog';
const OUTPUT_FILE = 'src/data/blogPosts.ts';

async function generateBlogPosts() {
  const files = await glob(`${CONTENT_DIR}/**/*.md`);

  const posts = files.map((file, index) => {
    const content = fs.readFileSync(file, 'utf-8');
    const { data, content: body } = matter(content);

    return {
      id: index + 1,
      title: data.title,
      type: data.type,
      date: new Date(data.date).toISOString().split('T')[0],
      excerpt: data.excerpt,
      content: body.trim(),
      tags: data.tags || []
    };
  });

  // Sort by date, newest first
  posts.sort((a, b) => new Date(b.date) - new Date(a.date));

  const output = `// Auto-generated from markdown files in content/blog
// DO NOT EDIT THIS FILE DIRECTLY - Edit the markdown files instead
// Run 'npm run generate-content' to regenerate

export interface BlogPost {
  id: number;
  title: string;
  type: 'divrei-torah' | 'reflection';
  date: string;
  excerpt: string;
  content: string;
  tags: string[];
}

export const blogPosts: BlogPost[] = ${JSON.stringify(posts, null, 2)};

export const getPostById = (id: number): BlogPost | undefined => {
  return blogPosts.find(post => post.id === id);
};

export const getPostsByType = (type: 'divrei-torah' | 'reflection' | 'all'): BlogPost[] => {
  if (type === 'all') return blogPosts;
  return blogPosts.filter(post => post.type === type);
};

export const getRecentPosts = (count: number = 3): BlogPost[] => {
  return [...blogPosts]
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, count);
};
`;

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
  console.log(`✅ Generated ${posts.length} blog posts to ${OUTPUT_FILE}`);
}

generateBlogPosts().catch(console.error);
